# Autogenerated wrapper script for GeographicLib_jll for x86_64-linux-gnu-cxx11
export CartConvert, ConicProj, GeoConvert, GeodSolve, GeodesicProj, GeoidEval, Gravity, MagneticField, Planimeter, RhumbSolve, TransverseMercatorProj, libGeographic

JLLWrappers.@generate_wrapper_header("GeographicLib")
JLLWrappers.@declare_executable_product(CartConvert)
JLLWrappers.@declare_executable_product(ConicProj)
JLLWrappers.@declare_executable_product(GeoConvert)
JLLWrappers.@declare_executable_product(GeodSolve)
JLLWrappers.@declare_executable_product(GeodesicProj)
JLLWrappers.@declare_executable_product(GeoidEval)
JLLWrappers.@declare_executable_product(Gravity)
JLLWrappers.@declare_executable_product(MagneticField)
JLLWrappers.@declare_executable_product(Planimeter)
JLLWrappers.@declare_executable_product(RhumbSolve)
JLLWrappers.@declare_executable_product(TransverseMercatorProj)
JLLWrappers.@declare_library_product(libGeographic, "libGeographic.so.19")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        CartConvert,
        "bin/CartConvert",
    )

    JLLWrappers.@init_executable_product(
        ConicProj,
        "bin/ConicProj",
    )

    JLLWrappers.@init_executable_product(
        GeoConvert,
        "bin/GeoConvert",
    )

    JLLWrappers.@init_executable_product(
        GeodSolve,
        "bin/GeodSolve",
    )

    JLLWrappers.@init_executable_product(
        GeodesicProj,
        "bin/GeodesicProj",
    )

    JLLWrappers.@init_executable_product(
        GeoidEval,
        "bin/GeoidEval",
    )

    JLLWrappers.@init_executable_product(
        Gravity,
        "bin/Gravity",
    )

    JLLWrappers.@init_executable_product(
        MagneticField,
        "bin/MagneticField",
    )

    JLLWrappers.@init_executable_product(
        Planimeter,
        "bin/Planimeter",
    )

    JLLWrappers.@init_executable_product(
        RhumbSolve,
        "bin/RhumbSolve",
    )

    JLLWrappers.@init_executable_product(
        TransverseMercatorProj,
        "bin/TransverseMercatorProj",
    )

    JLLWrappers.@init_library_product(
        libGeographic,
        "lib/libGeographic.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
